services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=derrick
      - POSTGRES_PASSWORD=rose
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/